[forest]
url = "https://frogofjuly.github.io/"
trees = ["trees"]                   # The directories in which your trees are stored
# assets = ["assets"]                  # The directories in which your assets are stored
[forest]

